/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const TaskContent = IDL.Record({
  'details' : IDL.Variant({
    'automationWorkflows' : IDL.Record({
      'status' : IDL.Vec(IDL.Text),
      'workflows' : IDL.Vec(IDL.Text),
    }),
    'seoTasks' : IDL.Record({
      'status' : IDL.Vec(IDL.Text),
      'tasks' : IDL.Vec(IDL.Text),
    }),
    'chatbotFlows' : IDL.Record({
      'flows' : IDL.Vec(IDL.Text),
      'messages' : IDL.Vec(IDL.Text),
    }),
    'adCampaignDetails' : IDL.Record({
      'ads' : IDL.Vec(IDL.Text),
      'channels' : IDL.Vec(IDL.Text),
    }),
    'siteArchitecture' : IDL.Record({
      'navigation' : IDL.Vec(IDL.Text),
      'pages' : IDL.Vec(IDL.Text),
    }),
    'domainStrategy' : IDL.Record({
      'domains' : IDL.Vec(IDL.Text),
      'criteria' : IDL.Vec(IDL.Text),
    }),
    'branding' : IDL.Record({
      'assets' : IDL.Vec(IDL.Text),
      'requirements' : IDL.Vec(IDL.Text),
    }),
    'socialMediaPlans' : IDL.Record({
      'platforms' : IDL.Vec(IDL.Text),
      'posts' : IDL.Vec(IDL.Text),
    }),
    'legalStructure' : IDL.Record({
      'progress' : IDL.Vec(IDL.Text),
      'items' : IDL.Vec(IDL.Text),
    }),
    'crmStages' : IDL.Record({
      'stages' : IDL.Vec(IDL.Text),
      'contacts' : IDL.Vec(IDL.Text),
    }),
    'optimizationMetrics' : IDL.Record({
      'metrics' : IDL.Vec(IDL.Text),
      'values' : IDL.Vec(IDL.Text),
    }),
    'businessModel' : IDL.Record({
      'answers' : IDL.Vec(IDL.Text),
      'questions' : IDL.Vec(IDL.Text),
    }),
  }),
  'milestone' : IDL.Nat,
  'phase' : IDL.Nat,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'content' : TaskContent,
  'completed' : IDL.Bool,
  'description' : IDL.Text,
  'dueTime' : Time,
  'notes' : IDL.Text,
  'milestone' : IDL.Nat,
  'phase' : IDL.Nat,
});
export const AdsMetrics = IDL.Record({
  'month' : IDL.Text,
  'leads' : IDL.Nat,
  'spent' : IDL.Float64,
  'appointments' : IDL.Nat,
  'converted' : IDL.Nat,
});
export const Milestone = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'progress' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addAdsMetrics' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'addMilestone' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'addTask' : IDL.Func(
      [IDL.Text, Time, IDL.Nat, IDL.Nat, IDL.Text, TaskContent],
      [IDL.Nat],
      [],
    ),
  'addTaskNotes' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'clearCompletedTasks' : IDL.Func([], [], []),
  'clearIncompleteTasks' : IDL.Func([], [], []),
  'completeTask' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'editTask' : IDL.Func(
      [IDL.Nat, IDL.Text, Time, IDL.Nat, IDL.Nat, TaskContent],
      [],
      [],
    ),
  'getActiveTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getAdsMetricsByMonth' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(AdsMetrics)],
      ['query'],
    ),
  'getAllAdsMetrics' : IDL.Func([], [IDL.Vec(AdsMetrics)], ['query']),
  'getAllMilestones' : IDL.Func([], [IDL.Vec(Milestone)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getCompletedTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getMilestone' : IDL.Func([IDL.Nat], [IDL.Opt(Milestone)], ['query']),
  'getTasksByMilestone' : IDL.Func([IDL.Nat], [IDL.Vec(Task)], ['query']),
  'getTasksByPhase' : IDL.Func([IDL.Nat], [IDL.Vec(Task)], ['query']),
  'updateMilestoneProgress' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const TaskContent = IDL.Record({
    'details' : IDL.Variant({
      'automationWorkflows' : IDL.Record({
        'status' : IDL.Vec(IDL.Text),
        'workflows' : IDL.Vec(IDL.Text),
      }),
      'seoTasks' : IDL.Record({
        'status' : IDL.Vec(IDL.Text),
        'tasks' : IDL.Vec(IDL.Text),
      }),
      'chatbotFlows' : IDL.Record({
        'flows' : IDL.Vec(IDL.Text),
        'messages' : IDL.Vec(IDL.Text),
      }),
      'adCampaignDetails' : IDL.Record({
        'ads' : IDL.Vec(IDL.Text),
        'channels' : IDL.Vec(IDL.Text),
      }),
      'siteArchitecture' : IDL.Record({
        'navigation' : IDL.Vec(IDL.Text),
        'pages' : IDL.Vec(IDL.Text),
      }),
      'domainStrategy' : IDL.Record({
        'domains' : IDL.Vec(IDL.Text),
        'criteria' : IDL.Vec(IDL.Text),
      }),
      'branding' : IDL.Record({
        'assets' : IDL.Vec(IDL.Text),
        'requirements' : IDL.Vec(IDL.Text),
      }),
      'socialMediaPlans' : IDL.Record({
        'platforms' : IDL.Vec(IDL.Text),
        'posts' : IDL.Vec(IDL.Text),
      }),
      'legalStructure' : IDL.Record({
        'progress' : IDL.Vec(IDL.Text),
        'items' : IDL.Vec(IDL.Text),
      }),
      'crmStages' : IDL.Record({
        'stages' : IDL.Vec(IDL.Text),
        'contacts' : IDL.Vec(IDL.Text),
      }),
      'optimizationMetrics' : IDL.Record({
        'metrics' : IDL.Vec(IDL.Text),
        'values' : IDL.Vec(IDL.Text),
      }),
      'businessModel' : IDL.Record({
        'answers' : IDL.Vec(IDL.Text),
        'questions' : IDL.Vec(IDL.Text),
      }),
    }),
    'milestone' : IDL.Nat,
    'phase' : IDL.Nat,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'content' : TaskContent,
    'completed' : IDL.Bool,
    'description' : IDL.Text,
    'dueTime' : Time,
    'notes' : IDL.Text,
    'milestone' : IDL.Nat,
    'phase' : IDL.Nat,
  });
  const AdsMetrics = IDL.Record({
    'month' : IDL.Text,
    'leads' : IDL.Nat,
    'spent' : IDL.Float64,
    'appointments' : IDL.Nat,
    'converted' : IDL.Nat,
  });
  const Milestone = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'progress' : IDL.Nat,
  });
  
  return IDL.Service({
    'addAdsMetrics' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'addMilestone' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'addTask' : IDL.Func(
        [IDL.Text, Time, IDL.Nat, IDL.Nat, IDL.Text, TaskContent],
        [IDL.Nat],
        [],
      ),
    'addTaskNotes' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'clearCompletedTasks' : IDL.Func([], [], []),
    'clearIncompleteTasks' : IDL.Func([], [], []),
    'completeTask' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'editTask' : IDL.Func(
        [IDL.Nat, IDL.Text, Time, IDL.Nat, IDL.Nat, TaskContent],
        [],
        [],
      ),
    'getActiveTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getAdsMetricsByMonth' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AdsMetrics)],
        ['query'],
      ),
    'getAllAdsMetrics' : IDL.Func([], [IDL.Vec(AdsMetrics)], ['query']),
    'getAllMilestones' : IDL.Func([], [IDL.Vec(Milestone)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getCompletedTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getMilestone' : IDL.Func([IDL.Nat], [IDL.Opt(Milestone)], ['query']),
    'getTasksByMilestone' : IDL.Func([IDL.Nat], [IDL.Vec(Task)], ['query']),
    'getTasksByPhase' : IDL.Func([IDL.Nat], [IDL.Vec(Task)], ['query']),
    'updateMilestoneProgress' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };