/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdsMetrics {
  'month' : string,
  'leads' : bigint,
  'spent' : number,
  'appointments' : bigint,
  'converted' : bigint,
}
export interface Task {
  'id' : bigint,
  'content' : TaskContent,
  'completed' : boolean,
  'description' : string,
  'dueTime' : Time,
  'notes' : string,
  'milestone' : bigint,
  'phase' : bigint,
}
export interface TaskContent {
  'details' : {
      'automationWorkflows' : {
        'status' : Array<string>,
        'workflows' : Array<string>,
      }
    } |
    { 'seoTasks' : { 'status' : Array<string>, 'tasks' : Array<string> } } |
    {
      'chatbotFlows' : { 'flows' : Array<string>, 'messages' : Array<string> }
    } |
    {
      'adCampaignDetails' : {
        'ads' : Array<string>,
        'channels' : Array<string>,
      }
    } |
    {
      'siteArchitecture' : {
        'navigation' : Array<string>,
        'pages' : Array<string>,
      }
    } |
    {
      'domainStrategy' : {
        'domains' : Array<string>,
        'criteria' : Array<string>,
      }
    } |
    {
      'branding' : { 'assets' : Array<string>, 'requirements' : Array<string> }
    } |
    {
      'socialMediaPlans' : {
        'platforms' : Array<string>,
        'posts' : Array<string>,
      }
    } |
    {
      'legalStructure' : { 'progress' : Array<string>, 'items' : Array<string> }
    } |
    { 'crmStages' : { 'stages' : Array<string>, 'contacts' : Array<string> } } |
    {
      'optimizationMetrics' : {
        'metrics' : Array<string>,
        'values' : Array<string>,
      }
    } |
    {
      'businessModel' : {
        'answers' : Array<string>,
        'questions' : Array<string>,
      }
    },
  'milestone' : bigint,
  'phase' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'addAdsMetrics' : ActorMethod<
    [string, number, bigint, bigint, bigint],
    undefined
  >,
  'addTask' : ActorMethod<
    [string, Time, bigint, bigint, string, TaskContent],
    bigint
  >,
  'addTaskNotes' : ActorMethod<[bigint, string], undefined>,
  'clearCompletedTasks' : ActorMethod<[], undefined>,
  'clearIncompleteTasks' : ActorMethod<[], undefined>,
  'completeTask' : ActorMethod<[bigint, boolean], undefined>,
  'editTask' : ActorMethod<
    [bigint, string, Time, bigint, bigint, TaskContent],
    undefined
  >,
  'getActiveTasks' : ActorMethod<[], Array<Task>>,
  'getAdsMetricsByMonth' : ActorMethod<[string], [] | [AdsMetrics]>,
  'getAllAdsMetrics' : ActorMethod<[], Array<AdsMetrics>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getCompletedTasks' : ActorMethod<[], Array<Task>>,
  'getTasksByMilestone' : ActorMethod<[bigint], Array<Task>>,
  'getTasksByPhase' : ActorMethod<[bigint], Array<Task>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];