/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Task {
    id: bigint;
    content: TaskContent;
    completed: boolean;
    description: string;
    dueTime: Time;
    notes: string;
    milestone: bigint;
    phase: bigint;
}
export interface TaskContent {
    details: {
        __kind__: "automationWorkflows";
        automationWorkflows: {
            status: Array<string>;
            workflows: Array<string>;
        };
    } | {
        __kind__: "seoTasks";
        seoTasks: {
            status: Array<string>;
            tasks: Array<string>;
        };
    } | {
        __kind__: "chatbotFlows";
        chatbotFlows: {
            flows: Array<string>;
            messages: Array<string>;
        };
    } | {
        __kind__: "adCampaignDetails";
        adCampaignDetails: {
            ads: Array<string>;
            channels: Array<string>;
        };
    } | {
        __kind__: "siteArchitecture";
        siteArchitecture: {
            navigation: Array<string>;
            pages: Array<string>;
        };
    } | {
        __kind__: "domainStrategy";
        domainStrategy: {
            domains: Array<string>;
            criteria: Array<string>;
        };
    } | {
        __kind__: "branding";
        branding: {
            assets: Array<string>;
            requirements: Array<string>;
        };
    } | {
        __kind__: "socialMediaPlans";
        socialMediaPlans: {
            platforms: Array<string>;
            posts: Array<string>;
        };
    } | {
        __kind__: "legalStructure";
        legalStructure: {
            progress: Array<string>;
            items: Array<string>;
        };
    } | {
        __kind__: "crmStages";
        crmStages: {
            stages: Array<string>;
            contacts: Array<string>;
        };
    } | {
        __kind__: "optimizationMetrics";
        optimizationMetrics: {
            metrics: Array<string>;
            values: Array<string>;
        };
    } | {
        __kind__: "businessModel";
        businessModel: {
            answers: Array<string>;
            questions: Array<string>;
        };
    };
    milestone: bigint;
    phase: bigint;
}
export type Time = bigint;
export interface Milestone {
    id: bigint;
    name: string;
    description: string;
    progress: bigint;
}
export interface AdsMetrics {
    month: string;
    leads: bigint;
    spent: number;
    appointments: bigint;
    converted: bigint;
}
export interface backendInterface {
    addAdsMetrics(month: string, spent: number, leads: bigint, appointments: bigint, converted: bigint): Promise<void>;
    addMilestone(id: bigint, name: string, description: string): Promise<void>;
    addTask(description: string, dueTime: Time, phase: bigint, milestone: bigint, notes: string, content: TaskContent): Promise<bigint>;
    addTaskNotes(taskId: bigint, notes: string): Promise<void>;
    clearCompletedTasks(): Promise<void>;
    clearIncompleteTasks(): Promise<void>;
    completeTask(taskId: bigint, completedVal: boolean): Promise<void>;
    editTask(taskId: bigint, newDescription: string, newDueTime: Time, newPhase: bigint, newMilestone: bigint, newContent: TaskContent): Promise<void>;
    getActiveTasks(): Promise<Array<Task>>;
    getAdsMetricsByMonth(month: string): Promise<AdsMetrics | null>;
    getAllAdsMetrics(): Promise<Array<AdsMetrics>>;
    getAllMilestones(): Promise<Array<Milestone>>;
    getAllTasks(): Promise<Array<Task>>;
    getCompletedTasks(): Promise<Array<Task>>;
    getMilestone(milestoneId: bigint): Promise<Milestone | null>;
    getTasksByMilestone(milestone: bigint): Promise<Array<Task>>;
    getTasksByPhase(phase: bigint): Promise<Array<Task>>;
    updateMilestoneProgress(milestoneId: bigint, progress: bigint): Promise<boolean>;
}
import type { AdsMetrics as _AdsMetrics, Milestone as _Milestone, Task as _Task, TaskContent as _TaskContent, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAdsMetrics(arg0: string, arg1: number, arg2: bigint, arg3: bigint, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdsMetrics(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdsMetrics(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addMilestone(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMilestone(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMilestone(arg0, arg1, arg2);
            return result;
        }
    }
    async addTask(arg0: string, arg1: Time, arg2: bigint, arg3: bigint, arg4: string, arg5: TaskContent): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTask(arg0, arg1, arg2, arg3, arg4, to_candid_TaskContent_n1(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTask(arg0, arg1, arg2, arg3, arg4, to_candid_TaskContent_n1(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async addTaskNotes(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTaskNotes(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTaskNotes(arg0, arg1);
            return result;
        }
    }
    async clearCompletedTasks(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCompletedTasks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCompletedTasks();
            return result;
        }
    }
    async clearIncompleteTasks(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearIncompleteTasks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearIncompleteTasks();
            return result;
        }
    }
    async completeTask(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeTask(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeTask(arg0, arg1);
            return result;
        }
    }
    async editTask(arg0: bigint, arg1: string, arg2: Time, arg3: bigint, arg4: bigint, arg5: TaskContent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editTask(arg0, arg1, arg2, arg3, arg4, to_candid_TaskContent_n1(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editTask(arg0, arg1, arg2, arg3, arg4, to_candid_TaskContent_n1(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async getActiveTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveTasks();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveTasks();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdsMetricsByMonth(arg0: string): Promise<AdsMetrics | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdsMetricsByMonth(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdsMetricsByMonth(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAdsMetrics(): Promise<Array<AdsMetrics>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAdsMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAdsMetrics();
            return result;
        }
    }
    async getAllMilestones(): Promise<Array<Milestone>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMilestones();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMilestones();
            return result;
        }
    }
    async getAllTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTasks();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTasks();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompletedTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompletedTasks();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompletedTasks();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMilestone(arg0: bigint): Promise<Milestone | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMilestone(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMilestone(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasksByMilestone(arg0: bigint): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksByMilestone(arg0);
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksByMilestone(arg0);
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasksByPhase(arg0: bigint): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksByPhase(arg0);
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksByPhase(arg0);
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMilestoneProgress(arg0: bigint, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMilestoneProgress(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMilestoneProgress(arg0, arg1);
            return result;
        }
    }
}
function from_candid_TaskContent_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskContent): TaskContent {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AdsMetrics]): AdsMetrics | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Milestone]): Milestone | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    content: _TaskContent;
    completed: boolean;
    description: string;
    dueTime: _Time;
    notes: string;
    milestone: bigint;
    phase: bigint;
}): {
    id: bigint;
    content: TaskContent;
    completed: boolean;
    description: string;
    dueTime: Time;
    notes: string;
    milestone: bigint;
    phase: bigint;
} {
    return {
        id: value.id,
        content: from_candid_TaskContent_n7(_uploadFile, _downloadFile, value.content),
        completed: value.completed,
        description: value.description,
        dueTime: value.dueTime,
        notes: value.notes,
        milestone: value.milestone,
        phase: value.phase
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    details: {
        automationWorkflows: {
            status: Array<string>;
            workflows: Array<string>;
        };
    } | {
        seoTasks: {
            status: Array<string>;
            tasks: Array<string>;
        };
    } | {
        chatbotFlows: {
            flows: Array<string>;
            messages: Array<string>;
        };
    } | {
        adCampaignDetails: {
            ads: Array<string>;
            channels: Array<string>;
        };
    } | {
        siteArchitecture: {
            navigation: Array<string>;
            pages: Array<string>;
        };
    } | {
        domainStrategy: {
            domains: Array<string>;
            criteria: Array<string>;
        };
    } | {
        branding: {
            assets: Array<string>;
            requirements: Array<string>;
        };
    } | {
        socialMediaPlans: {
            platforms: Array<string>;
            posts: Array<string>;
        };
    } | {
        legalStructure: {
            progress: Array<string>;
            items: Array<string>;
        };
    } | {
        crmStages: {
            stages: Array<string>;
            contacts: Array<string>;
        };
    } | {
        optimizationMetrics: {
            metrics: Array<string>;
            values: Array<string>;
        };
    } | {
        businessModel: {
            answers: Array<string>;
            questions: Array<string>;
        };
    };
    milestone: bigint;
    phase: bigint;
}): {
    details: {
        __kind__: "automationWorkflows";
        automationWorkflows: {
            status: Array<string>;
            workflows: Array<string>;
        };
    } | {
        __kind__: "seoTasks";
        seoTasks: {
            status: Array<string>;
            tasks: Array<string>;
        };
    } | {
        __kind__: "chatbotFlows";
        chatbotFlows: {
            flows: Array<string>;
            messages: Array<string>;
        };
    } | {
        __kind__: "adCampaignDetails";
        adCampaignDetails: {
            ads: Array<string>;
            channels: Array<string>;
        };
    } | {
        __kind__: "siteArchitecture";
        siteArchitecture: {
            navigation: Array<string>;
            pages: Array<string>;
        };
    } | {
        __kind__: "domainStrategy";
        domainStrategy: {
            domains: Array<string>;
            criteria: Array<string>;
        };
    } | {
        __kind__: "branding";
        branding: {
            assets: Array<string>;
            requirements: Array<string>;
        };
    } | {
        __kind__: "socialMediaPlans";
        socialMediaPlans: {
            platforms: Array<string>;
            posts: Array<string>;
        };
    } | {
        __kind__: "legalStructure";
        legalStructure: {
            progress: Array<string>;
            items: Array<string>;
        };
    } | {
        __kind__: "crmStages";
        crmStages: {
            stages: Array<string>;
            contacts: Array<string>;
        };
    } | {
        __kind__: "optimizationMetrics";
        optimizationMetrics: {
            metrics: Array<string>;
            values: Array<string>;
        };
    } | {
        __kind__: "businessModel";
        businessModel: {
            answers: Array<string>;
            questions: Array<string>;
        };
    };
    milestone: bigint;
    phase: bigint;
} {
    return {
        details: from_candid_variant_n9(_uploadFile, _downloadFile, value.details),
        milestone: value.milestone,
        phase: value.phase
    };
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    automationWorkflows: {
        status: Array<string>;
        workflows: Array<string>;
    };
} | {
    seoTasks: {
        status: Array<string>;
        tasks: Array<string>;
    };
} | {
    chatbotFlows: {
        flows: Array<string>;
        messages: Array<string>;
    };
} | {
    adCampaignDetails: {
        ads: Array<string>;
        channels: Array<string>;
    };
} | {
    siteArchitecture: {
        navigation: Array<string>;
        pages: Array<string>;
    };
} | {
    domainStrategy: {
        domains: Array<string>;
        criteria: Array<string>;
    };
} | {
    branding: {
        assets: Array<string>;
        requirements: Array<string>;
    };
} | {
    socialMediaPlans: {
        platforms: Array<string>;
        posts: Array<string>;
    };
} | {
    legalStructure: {
        progress: Array<string>;
        items: Array<string>;
    };
} | {
    crmStages: {
        stages: Array<string>;
        contacts: Array<string>;
    };
} | {
    optimizationMetrics: {
        metrics: Array<string>;
        values: Array<string>;
    };
} | {
    businessModel: {
        answers: Array<string>;
        questions: Array<string>;
    };
}): {
    __kind__: "automationWorkflows";
    automationWorkflows: {
        status: Array<string>;
        workflows: Array<string>;
    };
} | {
    __kind__: "seoTasks";
    seoTasks: {
        status: Array<string>;
        tasks: Array<string>;
    };
} | {
    __kind__: "chatbotFlows";
    chatbotFlows: {
        flows: Array<string>;
        messages: Array<string>;
    };
} | {
    __kind__: "adCampaignDetails";
    adCampaignDetails: {
        ads: Array<string>;
        channels: Array<string>;
    };
} | {
    __kind__: "siteArchitecture";
    siteArchitecture: {
        navigation: Array<string>;
        pages: Array<string>;
    };
} | {
    __kind__: "domainStrategy";
    domainStrategy: {
        domains: Array<string>;
        criteria: Array<string>;
    };
} | {
    __kind__: "branding";
    branding: {
        assets: Array<string>;
        requirements: Array<string>;
    };
} | {
    __kind__: "socialMediaPlans";
    socialMediaPlans: {
        platforms: Array<string>;
        posts: Array<string>;
    };
} | {
    __kind__: "legalStructure";
    legalStructure: {
        progress: Array<string>;
        items: Array<string>;
    };
} | {
    __kind__: "crmStages";
    crmStages: {
        stages: Array<string>;
        contacts: Array<string>;
    };
} | {
    __kind__: "optimizationMetrics";
    optimizationMetrics: {
        metrics: Array<string>;
        values: Array<string>;
    };
} | {
    __kind__: "businessModel";
    businessModel: {
        answers: Array<string>;
        questions: Array<string>;
    };
} {
    return "automationWorkflows" in value ? {
        __kind__: "automationWorkflows",
        automationWorkflows: value.automationWorkflows
    } : "seoTasks" in value ? {
        __kind__: "seoTasks",
        seoTasks: value.seoTasks
    } : "chatbotFlows" in value ? {
        __kind__: "chatbotFlows",
        chatbotFlows: value.chatbotFlows
    } : "adCampaignDetails" in value ? {
        __kind__: "adCampaignDetails",
        adCampaignDetails: value.adCampaignDetails
    } : "siteArchitecture" in value ? {
        __kind__: "siteArchitecture",
        siteArchitecture: value.siteArchitecture
    } : "domainStrategy" in value ? {
        __kind__: "domainStrategy",
        domainStrategy: value.domainStrategy
    } : "branding" in value ? {
        __kind__: "branding",
        branding: value.branding
    } : "socialMediaPlans" in value ? {
        __kind__: "socialMediaPlans",
        socialMediaPlans: value.socialMediaPlans
    } : "legalStructure" in value ? {
        __kind__: "legalStructure",
        legalStructure: value.legalStructure
    } : "crmStages" in value ? {
        __kind__: "crmStages",
        crmStages: value.crmStages
    } : "optimizationMetrics" in value ? {
        __kind__: "optimizationMetrics",
        optimizationMetrics: value.optimizationMetrics
    } : "businessModel" in value ? {
        __kind__: "businessModel",
        businessModel: value.businessModel
    } : value;
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n5(_uploadFile, _downloadFile, x));
}
function to_candid_TaskContent_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskContent): _TaskContent {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    details: {
        __kind__: "automationWorkflows";
        automationWorkflows: {
            status: Array<string>;
            workflows: Array<string>;
        };
    } | {
        __kind__: "seoTasks";
        seoTasks: {
            status: Array<string>;
            tasks: Array<string>;
        };
    } | {
        __kind__: "chatbotFlows";
        chatbotFlows: {
            flows: Array<string>;
            messages: Array<string>;
        };
    } | {
        __kind__: "adCampaignDetails";
        adCampaignDetails: {
            ads: Array<string>;
            channels: Array<string>;
        };
    } | {
        __kind__: "siteArchitecture";
        siteArchitecture: {
            navigation: Array<string>;
            pages: Array<string>;
        };
    } | {
        __kind__: "domainStrategy";
        domainStrategy: {
            domains: Array<string>;
            criteria: Array<string>;
        };
    } | {
        __kind__: "branding";
        branding: {
            assets: Array<string>;
            requirements: Array<string>;
        };
    } | {
        __kind__: "socialMediaPlans";
        socialMediaPlans: {
            platforms: Array<string>;
            posts: Array<string>;
        };
    } | {
        __kind__: "legalStructure";
        legalStructure: {
            progress: Array<string>;
            items: Array<string>;
        };
    } | {
        __kind__: "crmStages";
        crmStages: {
            stages: Array<string>;
            contacts: Array<string>;
        };
    } | {
        __kind__: "optimizationMetrics";
        optimizationMetrics: {
            metrics: Array<string>;
            values: Array<string>;
        };
    } | {
        __kind__: "businessModel";
        businessModel: {
            answers: Array<string>;
            questions: Array<string>;
        };
    };
    milestone: bigint;
    phase: bigint;
}): {
    details: {
        automationWorkflows: {
            status: Array<string>;
            workflows: Array<string>;
        };
    } | {
        seoTasks: {
            status: Array<string>;
            tasks: Array<string>;
        };
    } | {
        chatbotFlows: {
            flows: Array<string>;
            messages: Array<string>;
        };
    } | {
        adCampaignDetails: {
            ads: Array<string>;
            channels: Array<string>;
        };
    } | {
        siteArchitecture: {
            navigation: Array<string>;
            pages: Array<string>;
        };
    } | {
        domainStrategy: {
            domains: Array<string>;
            criteria: Array<string>;
        };
    } | {
        branding: {
            assets: Array<string>;
            requirements: Array<string>;
        };
    } | {
        socialMediaPlans: {
            platforms: Array<string>;
            posts: Array<string>;
        };
    } | {
        legalStructure: {
            progress: Array<string>;
            items: Array<string>;
        };
    } | {
        crmStages: {
            stages: Array<string>;
            contacts: Array<string>;
        };
    } | {
        optimizationMetrics: {
            metrics: Array<string>;
            values: Array<string>;
        };
    } | {
        businessModel: {
            answers: Array<string>;
            questions: Array<string>;
        };
    };
    milestone: bigint;
    phase: bigint;
} {
    return {
        details: to_candid_variant_n3(_uploadFile, _downloadFile, value.details),
        milestone: value.milestone,
        phase: value.phase
    };
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "automationWorkflows";
    automationWorkflows: {
        status: Array<string>;
        workflows: Array<string>;
    };
} | {
    __kind__: "seoTasks";
    seoTasks: {
        status: Array<string>;
        tasks: Array<string>;
    };
} | {
    __kind__: "chatbotFlows";
    chatbotFlows: {
        flows: Array<string>;
        messages: Array<string>;
    };
} | {
    __kind__: "adCampaignDetails";
    adCampaignDetails: {
        ads: Array<string>;
        channels: Array<string>;
    };
} | {
    __kind__: "siteArchitecture";
    siteArchitecture: {
        navigation: Array<string>;
        pages: Array<string>;
    };
} | {
    __kind__: "domainStrategy";
    domainStrategy: {
        domains: Array<string>;
        criteria: Array<string>;
    };
} | {
    __kind__: "branding";
    branding: {
        assets: Array<string>;
        requirements: Array<string>;
    };
} | {
    __kind__: "socialMediaPlans";
    socialMediaPlans: {
        platforms: Array<string>;
        posts: Array<string>;
    };
} | {
    __kind__: "legalStructure";
    legalStructure: {
        progress: Array<string>;
        items: Array<string>;
    };
} | {
    __kind__: "crmStages";
    crmStages: {
        stages: Array<string>;
        contacts: Array<string>;
    };
} | {
    __kind__: "optimizationMetrics";
    optimizationMetrics: {
        metrics: Array<string>;
        values: Array<string>;
    };
} | {
    __kind__: "businessModel";
    businessModel: {
        answers: Array<string>;
        questions: Array<string>;
    };
}): {
    automationWorkflows: {
        status: Array<string>;
        workflows: Array<string>;
    };
} | {
    seoTasks: {
        status: Array<string>;
        tasks: Array<string>;
    };
} | {
    chatbotFlows: {
        flows: Array<string>;
        messages: Array<string>;
    };
} | {
    adCampaignDetails: {
        ads: Array<string>;
        channels: Array<string>;
    };
} | {
    siteArchitecture: {
        navigation: Array<string>;
        pages: Array<string>;
    };
} | {
    domainStrategy: {
        domains: Array<string>;
        criteria: Array<string>;
    };
} | {
    branding: {
        assets: Array<string>;
        requirements: Array<string>;
    };
} | {
    socialMediaPlans: {
        platforms: Array<string>;
        posts: Array<string>;
    };
} | {
    legalStructure: {
        progress: Array<string>;
        items: Array<string>;
    };
} | {
    crmStages: {
        stages: Array<string>;
        contacts: Array<string>;
    };
} | {
    optimizationMetrics: {
        metrics: Array<string>;
        values: Array<string>;
    };
} | {
    businessModel: {
        answers: Array<string>;
        questions: Array<string>;
    };
} {
    return value.__kind__ === "automationWorkflows" ? {
        automationWorkflows: value.automationWorkflows
    } : value.__kind__ === "seoTasks" ? {
        seoTasks: value.seoTasks
    } : value.__kind__ === "chatbotFlows" ? {
        chatbotFlows: value.chatbotFlows
    } : value.__kind__ === "adCampaignDetails" ? {
        adCampaignDetails: value.adCampaignDetails
    } : value.__kind__ === "siteArchitecture" ? {
        siteArchitecture: value.siteArchitecture
    } : value.__kind__ === "domainStrategy" ? {
        domainStrategy: value.domainStrategy
    } : value.__kind__ === "branding" ? {
        branding: value.branding
    } : value.__kind__ === "socialMediaPlans" ? {
        socialMediaPlans: value.socialMediaPlans
    } : value.__kind__ === "legalStructure" ? {
        legalStructure: value.legalStructure
    } : value.__kind__ === "crmStages" ? {
        crmStages: value.crmStages
    } : value.__kind__ === "optimizationMetrics" ? {
        optimizationMetrics: value.optimizationMetrics
    } : value.__kind__ === "businessModel" ? {
        businessModel: value.businessModel
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
